general:
  batch_size: 64
  max_epochs: 3

model:
  model_type: resnet18
  lambda_bt: 0.005
  projection_hidden_dim: 2048
  projection_dim: 128
  input_size: [224, 224]
  optimizer_name: adam
  lr: 0.0001 # 1e-4
  weight_decay: 0.0
  warmup_lr: 3 # Epochs

data:
  train_path: i4ds/radio-sunburst-ecallisto-paths-df-v2
  train_split: train
  val_path: i4ds/radio-sunburst-ecallisto-paths-df-v2-TEST-SET-SPLIT
  val_split: train
  test_path: i4ds/radio-sunburst-ecallisto-paths-df-v2-TEST-SET-SPLIT
  test_split: validation
  frequency_masking_para: 80
  time_masking_para: 40
  freq_mask_method: max
  time_warp_w: 800
