general:
  batch_size: 64
  max_epochs: 25
  binary: True
  use_random_sampler: False
  use_class_weights: True

model:
  model_type: resnet34
  input_size: [128, 512]
  optimizer_name: adamw
  warmup_epochs: 12
  lr: 0.00023762695665743765
  label_smoothing: 0.11739565855800864
  weight_decay: 0.0005164989055101516

data:
  train_path: [i4ds/ecallisto_radio_sunburst, i4ds/ecallisto_radio_sunburst]
  train_split: [train, val]
  val_path: i4ds/ecallisto_radio_sunburst
  val_split: test
  test_path: i4ds/ecallisto_radio_sunburst
  test_split: test
  train_label_name: manual_label
  val_label_name: manual_label
  test_label_name: manual_label
  antennas_train: []
  antennas_val: []
  antennas_test: []
  reduce_non_burst: False
  custom_resize: False
  clip_to_range: False
  train_class_to_reduce: 0
  reduction_fraction: 0.2
  use_augmentation: True
  frequency_masking_para: 25
  time_masking_para: 70
  freq_mask_method: random
  time_warp_w: 389
  pred_path: i4ds/ecallisto_radio_sunburst
  pred_split: test

# https://wandb.ai/vincenzo-timmel/FlareSense-v2/runs/dfpxq6wo/overview