general:
  batch_size: 64
  max_epochs: 20
  binary: True
  use_random_sampler: False
  use_class_weights: True

model:
  model_type: resnet18
  input_size: [224, 224]
  optimizer_name: adam
  lr: 0.0021418348849082266
  label_smoothing: 0.1
  weight_decay: 0.0

data:
  train_path: i4ds/ecallisto_radio_sunburst
  train_split: train
  val_path: i4ds/ecallisto_radio_sunburst
  val_split: val
  test_path: i4ds/ecallisto_radio_sunburst
  test_split: test
  label_name: model_label
  antennas_train: []
  antennas_val: []
  antennas_test: []
  reduce_non_burst: False
  train_class_to_reduce: 0
  reduction_fraction: 0.2
  use_augmentation: True
  frequency_masking_para: 15
  time_masking_para: 0
  freq_mask_method: max
  time_warp_w: 293
