general:
  batch_size: 32
  max_epochs: 10
  binary: True
  use_random_sampler: False
  use_class_weights: True

model:
  model_type: resnet18
  input_size: [224, 244]
  optimizer_name: adamw
  lr: 1.0e-4

data:
  train_path: i4ds/radio-sunburst-ecallisto
  val_path: i4ds/radio-sunburst-ecallisto
  test_path: i4ds/radio-sunburst-ecallisto-binary-cleaned-by-cm
  reduce_non_burst: True
  train_class_to_reduce: 0
  reduction_fraction: 0.2
  simple_normalization: False
  use_augmentation: True
  freq_mask_param: 30
  time_masking_para: 0