general:
  batch_size: 32
  max_epochs: 30
  binary: False
  use_random_sampler: False
  use_class_weights: True

model:
  mean: 0.5721
  std: 0.1100
  size: [224, 244]

data:
  train_class_to_reduce: 0
  reduction_fraction: 0.2
  freq_mask_param: 30
  time_mask_param: 30
