general:
  batch_size: 32
  max_epochs: 15
  binary: True
  use_random_sampler: False
  use_class_weights: True

model:
  input_size: [224, 244]
  lr: 1.0e-4
  dropout: 0.2

data:
  reduce_non_burst: True
  train_class_to_reduce: 0
  reduction_fraction: 0.2
  simple_normalization: False
  use_augmentation: False
  freq_mask_param: 30
  time_mask_param: 30
