general:
  batch_size: 32
  max_epochs: 20
  binary: True
  use_random_sampler: False
  use_class_weights: True

model:
  model_type: resnet18
  input_size: [224, 224]
  optimizer_name: adam
  lr: 0.0021418348849082266

data:
  train_path: i4ds/radio-sunburst-ecallisto-paths-df-v2
  train_split: train
  val_path: i4ds/radio-sunburst-ecallisto-paths-df-v2
  val_split: validation
  test_path: i4ds/radio-sunburst-ecallisto-paths-df-v2
  test_split: test
  antennas_train: [
    "GLASGOW_01",
    "BIR_01",
    "ALASKA-HAARP_62",
    "ALASKA-COHOE_63",
    "AUSTRIA-UNIGRAZ_01",
    "Australia-ASSA_62",
    "HUMAIN_59",
    "MRO_59",
    "INDIA-OOTY_02",
    "SWISS-Landschlacht_62"
  ]
  antennas_val: [
    "MEXICO-FCFM-UANL_01",
    "USA-ARIZONA-ERAU_01",
    "GLASGOW_01",
    "EGYPT-Alexandria_02",
    "BIR_01",
    "ALASKA-HAARP_62",
    "MONGOLIA-UB_01",
    "KASI_59",
    "ALMATY_58",
    "MRO_61",
    "ALGERIA-CRAAG_59",
    "ALASKA-COHOE_63",
    "AUSTRIA-UNIGRAZ_01",
    "Australia-ASSA_02",
    "Australia-ASSA_62",
    "GERMANY-DLR_63",
    "HUMAIN_59",
    "INDIA-GAURI_01",
    "INDIA-OOTY_02",
    "MEXART_59",
    "MEXICO-LANCE-B_62",
    "NORWAY-EGERSUND_01",
    "SSRT_59",
    "SWISS-Landschlacht_62",
    "TRIEST_57"
  ]
  antennas_test: [
    "MEXICO-FCFM-UANL_01",
    "USA-ARIZONA-ERAU_01",
    "GLASGOW_01",
    "EGYPT-Alexandria_02",
    "BIR_01",
    "ALASKA-HAARP_62",
    "MONGOLIA-UB_01",
    "KASI_59",
    "ALMATY_58",
    "MRO_61",
    "ALGERIA-CRAAG_59",
    "ALASKA-COHOE_63",
    "AUSTRIA-UNIGRAZ_01",
    "Australia-ASSA_02",
    "Australia-ASSA_62",
    "GERMANY-DLR_63",
    "HUMAIN_59",
    "INDIA-GAURI_01",
    "INDIA-OOTY_02",
    "MEXART_59",
    "MEXICO-LANCE-B_62",
    "NORWAY-EGERSUND_01",
    "SSRT_59",
    "SWISS-Landschlacht_62",
    "TRIEST_57"
  ]
  reduce_non_burst: False
  train_class_to_reduce: 0
  reduction_fraction: 0.2
  use_augmentation: True
  frequency_masking_para: 15
  time_masking_para: 0
  freq_mask_method: max
  time_warp_w: 293
