general:
  batch_size: 32
  max_epochs: 20
  binary: True
  use_random_sampler: False
  use_class_weights: True

model:
  model_type: resnet18
  input_size: [224, 224]
  optimizer_name: adamw
  lr: 0.009092421294035468

data:
  train_path: i4ds/radio-sunburst-ecallisto-paths-df
  val_path: i4ds/radio-sunburst-ecallisto-paths-df
  test_path: i4ds/radio-sunburst-ecallisto-paths-df
  antennas: []
  reduce_non_burst: False
  train_class_to_reduce: 0
  reduction_fraction: 0.2
  use_augmentation: False
  frequency_masking_para: 30
  freq_mask_method: max
