general:
  batch_size: 32
  max_epochs: 1
  binary: True
  min_precision: 0.8 # Max Recall for min Precision Metric.
  use_random_sampler: False
  use_class_weights: True

model:
  input_size: [224, 244]
  lr: 1.0e-4

data:
  train_class_to_reduce: 0
  reduction_fraction: 0.2
  use_augmentation: False
  freq_mask_param: 30
  time_mask_param: 30
