general:
  batch_size: 32
  max_epochs: 10
  binary: True
  use_random_sampler: False
  use_class_weights: True

model:
  model_type: resnet18
  input_size: [224, 244]
  optimizer_name: adamw
  lr: 0.009092421294035468

data:
  train_path: i4ds/radio-sunburst-ecallisto
  val_path: i4ds/radio-sunburst-ecallisto
  test_path: i4ds/radio-sunburst-ecallisto-binary-cleaned-by-cm
  antennas: ['Australia-ASSA_62',
            'ALASKA-HAARP_62',
            'GLASGOW_01',
            'SWISS-Landschlacht_62',
            'ALASKA-COHOE_63',
            'GERMANY-DLR_63',
            'USA-ARIZONA-ERAU_01',
            'ALMATY_58',
            'Australia-ASSA_02',
            'ALGERIA-CRAAG_59',
            'MEXICO-LANCE-B_62'
            ]
  reduce_non_burst: False
  train_class_to_reduce: 0
  reduction_fraction: 0.2
  simple_normalization: False
  use_augmentation: False
  freq_mask_param: 30
